"""invoice_design_updates

Revision ID: 017a3df208d6
Revises: 696a0e21ba53
Create Date: 2026-01-12 19:57:08.763434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017a3df208d6'
down_revision: Union[str, Sequence[str], None] = '696a0e21ba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('tagline', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'tagline')
    op.drop_column('companies', 'pan')
    op.drop_column('companies', 'address_line2')
    op.drop_column('companies', 'address_line1')
    op.drop_column('clients', 'pan')
    op.drop_column('clients', 'address_line2')
    # ### end Alembic commands ###
