"""invoice_snapshot_and_rates_v2

Revision ID: 526abae4d9c6
Revises: 017a3df208d6
Create Date: 2026-01-21 10:56:16.864317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '526abae4d9c6'
down_revision: Union[str, Sequence[str], None] = '017a3df208d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index('ix_invoices_company_client', 'invoices', ['company_id', 'client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_company_client', table_name='invoices')
    op.drop_column('invoices', 'igst_rate')
    op.drop_column('invoices', 'sgst_rate')
    op.drop_column('invoices', 'cgst_rate')
    op.drop_column('invoices', 'invoice_snapshot')
    # ### end Alembic commands ###
