"""extended_company_profile_and_clients

Revision ID: b576bbb17a42
Revises: ad8e8eeced16
Create Date: 2026-01-10 18:40:06.302030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b576bbb17a42'
down_revision: Union[str, Sequence[str], None] = 'ad8e8eeced16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    op.add_column('companies', sa.Column('registered_address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('account_holder_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('ifsc_code', sa.String(length=11), nullable=True))
    op.add_column('companies', sa.Column('bank_pan', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('banner_image_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('signature_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('stamp_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stamp_url')
    op.drop_column('companies', 'signature_url')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'banner_image_url')
    op.drop_column('companies', 'bank_pan')
    op.drop_column('companies', 'ifsc_code')
    op.drop_column('companies', 'account_number')
    op.drop_column('companies', 'account_holder_name')
    op.drop_column('companies', 'bank_name')
    op.drop_column('companies', 'pan_number')
    op.drop_column('companies', 'pincode')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'registered_address')
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
